add appendFilePath method
sofastack/sofa-rpc pull request #1229
Opened 2022-08-02 08:09 UTC by EvenLjj

add appendFilePath method

2022-08-17 09:02 UTC, JervyShi requested changes

2022-08-21 05:24 UTC, EvenLjj commented on core/common/src/main/java/com/alipay/sofa/rpc/common/utils/FileUtils.java
> +    public static String appendFilePath(String base, String... left) {
OK, have modified.

2022-08-21 05:25 UTC, EvenLjj commented on core/common/src/main/java/com/alipay/sofa/rpc/common/utils/FileUtils.java
> +            sb.append("/");
> Use `File.pathSeparator` instead `/` for more compatibility.
OK, have modified, use `File.separatorChar` instead.

2022-08-21 05:26 UTC, EvenLjj commented on core/common/src/main/java/com/alipay/sofa/rpc/common/utils/FileUtils.java
> +            sb.append("/");
OK, have used `File.separatorChar` instead.

2022-08-21 09:15 UTC, JervyShi approved these changes
LGTM

2022-08-22 07:29 UTC, OrezzerO commented on core/common/src/test/java/com/alipay/sofa/rpc/common/utils/FileUtilsTest.java
> +        Assert.assertEquals("baseFilePath", FileUtils.appendFilePath("baseFilePath", null));
这里的结果是`baseFilePath/null` 是不是更符合规律? 或者我们将包含 null 值的入参,全部认为是异常场景?

2022-08-22 12:33 UTC, EvenLjj commented on core/common/src/test/java/com/alipay/sofa/rpc/common/utils/FileUtilsTest.java
> +        Assert.assertEquals("baseFilePath", FileUtils.appendFilePath("baseFilePath", null));
Ok, remove appendFilePath, can use Paths.get().toString() instead

2022-08-24 13:33 UTC, OrezzerO approved these changes
LGTM

2022-08-24 14:21 UTC, merged