fix triple multi classloader switch problem
sofastack/sofa-rpc pull request #1278
Opened 2022-11-09 13:56 UTC by EvenLjj

fix triple multi classloader switch problem.

2022-11-10 03:28 UTC, OrezzerO commented on remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/GenericServiceImpl.java
> +    private String getUniqueIdFromInvokeContext() {
这个方法在 UniqueIdInvoker 中已经实现了, 没必要再写一个,重复代码要不得. 另外可以考虑下将所有有关 UniqueId 的操作封装到 UniqueIdInvoker 中, 比如上面我们需要通过 uniqueIdinvoker
 获得对应的classloader, 这个操作也可以全部放在 uniqueIdinvoker 内部, providerConfig 对于 GenericServiceImpl 来说没什么用.

2022-11-10 03:28 UTC, OrezzerO commented on remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/server/triple/GenericServiceImplTest.java
> +        String key = ConfigUniqueNameGenerator.getUniqueName(providerConfig);
测试用例需要针对多 classLoader 的模拟再丰富一下

2022-11-10 03:34 UTC, zjulbj requested changes

2022-11-10 03:34 UTC, zjulbj commented on remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleServer.java
>              ServerServiceDefinition ssd = this.handlerRegistry.addService(serviceDefinition);
这个addService是通过service.getServiceDescriptor().getName()作为key的，这个值是类全名，是否会有问题

2023-01-03 06:04 UTC, EvenLjj commented on remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleServer.java
>              ServerServiceDefinition ssd = this.handlerRegistry.addService(serviceDefinition);
This key is the full name of the interface class. It mainly describes the method parameter definition of the interface. The request processing is proxy to UniqueIdInvoker.

2023-01-04 02:23 UTC, chuailiwu approved these changes

2023-01-05 02:44 UTC, Lo1nt approved these changes

2023-01-05 02:47 UTC, merged